baseURL = 'https://www.enixyu.com/'
copyright = "Copyright Enix Yu 2015 - {year}"
languageCode = 'en-US'
defaultContentLanguage = 'en'
theme = 'enchanted-lowkey'
title = "Enix Yu's Blog"
enableRobotsTXT = true
summaryLength = 15
pagination.pagerSize = 5

permalinks.posts = "/:contentbasename"
services.googleAnalytics.id = "G-F2R6FSZ1ZR"

params.font = 'Roboto, "Helvetica Neue", Helvetica, Arial, sans-serif'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
